### ISSUE TITLE
Show commit message

### ISSUE THREAD

**Issue by jkoepcke** [esc/git-big-picture#16]
I am not a python guru, so I solved this by setting the label of each "bubble" with the output of git show --oneline [sha1]. But there's a better way I suppose :)

This should be a milestone, not an issue.

**Comment by ericsmalling** [comment]
Pulled your fork, jkoepcke, and it works great for me.  Looking forward to it being pulled into the main

**Comment by esc** [comment]
@ericsmalling thanks for your feedback, but no pull-request was ever created and the comments I made were never addressed. 

Also, this project has been pretty much finished/dead for several years and it's unlikely that I'll find time to work on it in the future. In addition the state of python interfaces to git has changed significantly and if anyone wanted to work on this again, I would suggest looking at: 

https://github.com/libgit2/pygit2

For much more flexibility when it comes to querying git repos.

**Comment by ericsmalling** [comment]
That's cool - I just needed a quick visualization tool to drive home some branching examples and this fit the need.  (I didn't notice the age of this issue thread when I replied either :) )
