### ISSUE TITLE
NameError: name 'git' is not defined

### ISSUE THREAD

**Issue by Reithan** [esc/git-big-picture#21]
Trying to run this in an windows environment. I have python installed (tried v2 & 3), GitPython, GraphViz, and any run of setup, test, or git_big_picture all result in this error.

**Comment by gabrieldelaparra** [comment]
+1

**Comment by esc** [comment]
I am sorry, I don't use windows so I can not help you there. Have you tried GitBash and running it from there?

**Comment by esc** [comment]
Since I haven't received a reply to this yet, I would assume the problem no longer persists. If it does continue, please re-open

**Comment by Harfeur** [comment]
Hi! I can confirm that it works only with the Git Bash on Windows.
