### ISSUE TITLE
Real-world example images could not be opened

### ISSUE THREAD

**Issue by vkotovv** [esc/git-big-picture#22]
Looks like those URLs in real-world examples in the Screenshots section of the README (https://github.com/esc/git-big-picture/blame/master/README.rst#L79) are no longer working.

**Comment by rajvinjamuri** [comment]
+1

**Comment by esc** [comment]
@vkotovv @rajvinjamuri yes, sorry about that, the server went down. I have resurrected the images from an old backup, added then to the repo and fixed links:

https://github.com/esc/git-big-picture/commit/274b569c521a4fabb231a3a2c2cbee73101fd432
