### ISSUE TITLE
Error calling viewer

### ISSUE THREAD

**Issue by ranma2913** [esc/git-big-picture#33]
When running in the directory containing .git folder I get the below error:
```
git-big-picture -o our-project.png
fatal: Error calling viewer: 'firefox':
>>>[Errno 2] No such file or directory: 'firefox': 'firefox'

```

**Comment by ranma2913** [comment]
I have the following set in my ~/.gitconfig file:
```
[big-picture]
	viewer = firefox
```

**Comment by ranma2913** [comment]
I tried updating to:

```
[big-picture]
	viewer = /Applications/Firefox.app
```
Which generates the following message:
```
git-big-picture -o our-project.png
fatal: Error calling viewer: '/Applications/Firefox.app':
>>>[Errno 13] Permission denied: '/Applications/Firefox.app'
```

**Comment by ranma2913** [comment]
Any ideas how to setup a viewer in MacOS?

**Comment by esc** [comment]
I just tried with Chrome on the command line, like so:

```
$ git bp -v /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
```

Maybe a similar solution works for Firefox?

**Comment by esc** [comment]
@ranma2913 any news on this?

**Comment by esc** [comment]
@ranma2913 I will close this issue now, feel free to re-open should your problems persist
